#!/bin/bash -x

id=09_Olympiastadion

zero_value=1560
amplitude=600
c=1
w=320
h=180
camera_topic=/zed/right/image_rect_color
rc_topic=/mavros/rc/in
channel=0
src_dir=/media/dprylipko/sdcard/$id
dest_dir=behavioral_cloning/data/$id
preprocessing="resize rgb2gray perspective histEq"
transform_param=playground/perspective_transform.txt

for fold in train08 train09; do

python behavioral_cloning/tools/bag2hdf5.py --interpolate \
       --zero_value $zero_value \
       --amplitude $amplitude \
       --img_channels $c \
       --img_width $w \
       --img_height $h \
       --preprocessing $preprocessing \
       --perspective_param $transform_param \
       $src_dir/$fold.bag \
       $camera_topic \
       $rc_topic \
       $channel \
       $dest_dir/$fold.h5
done

exit

for fold in valid01 valid02; do

python behavioral_cloning/tools/bag2hdf5.py \
       --zero_value $zero_value \
       --amplitude $amplitude \
       --img_channels $c \
       --img_width $w \
       --img_height $h \
       --preprocessing $preprocessing \
       --perspective_param $transform_param \
       $src_dir/$fold.bag \
       $camera_topic \
       $rc_topic \
       $channel \
       $dest_dir/$fold.h5
done

