#!/bin/bash
dest_dir=dump/train
input=data/train01.bag

mkdir -p $dest_dir/camera/img
python tools/bag2images.py --stop_after 500 $input $dest_dir/camera.csv $dest_dir/camera/img /zed/right/image_rect_color
